# Wait 20 milliseconds for starship to check files under the current directory.
scan_timeout = 20

# Disable the blank line at the start of the prompt
add_newline = false

format = """
$time\
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$status\
$shell\
$character"""

[time]
disabled = false
format = "[$time]($style) "

[shlvl]
disabled = false
threshold = 2
symbol = "↕️"

[jobs]
disabled = false
threshold = 1

[directory]
truncation_length = 0
truncate_to_repo = false
